#!/usr/bin/expect

# Runs KU REPO bash script
spawn /home/pinkg/Scripts/Bash/git_pull_KU.sh

# Waits for username prompt and sends answer
expect "Username for 'https://ku.bootcampcontent.com':\r"
send -- "grahmik@gmail.com\r"

# Waits for password prompt and sends answer
expect "Password for 'https://grahmik@gmail.com@ku.bootcampcontent.com':\r"
send -- "!s3bR83WKBDRYAK\r"

# End of file
expect eof
